application:
  port: 8000
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
email_client:
  base_url: "localhost"
  sender_email: "testmail@test.com"
  api_token: "my-api-token"
  secret_token: "my-secret-api-token"
  timeout_milliseconds: 10000
